name: HeadHunter
main: com.gmail.scottmwoodward.headhunter.HeadHunter
version: 1.3.6

commands:
  spawnhead:
    description: Spawns a copy of the specified player's head into your inventory.
    usage: /spawnhead <playername>
    permission: headhunter.command.spawnhead
    
permissions:
  headhunter.command.spawnhead:
    description: Gives access to /spawnhead
    default: op